### ISSUE TITLE
Add (yet invisible) Meta-Nodes as Border-Nodes

### ISSUE THREAD

**Issue by Shadow992** [UniFormal/TGView#11]
Add Meta-Nodes as Border-Nodes

**Comment by Jazzpirate** [comment]
Careful; the way you put it, it seems you're conflating two different issues:
1) make meta-edges toggleable (i.e. just make the edges with type "meta" visible or invisible)
2) adding border-nodes; meaning those nodes that are referenced by edges, but don't appear in the "nodes"-list of the json.
But the border-nodes aren't necessarily meta-theories etc. ;)

**Comment by Shadow992** [comment]
Implemented with commit 84397357492811e5957b40ce7abc28b87ecedb65

But keep in mind: Somehow we have to be able to disable Border-Nodes if needed/wanted
