### ISSUE TITLE
Hierarchy view with MitM set does not work

### ISSUE THREAD

**Issue by JacquesCarette** [UniFormal/TGView#12]
More specifically, when going to
https://mathhub.info/mh/mmt/graphs/tgview.html?type=pgraph&graphdata=http://mathhub.info/MitM
and trying to change from the default view to hierarchy, it just spins and never comes back.

Tried on Chrome on Mac and Firefox on Linux, same behaviour.

**Comment by Shadow992** [comment]
This already was fixed with the following commit:

https://github.com/UniFormal/TGView/commit/af1bf27c9d216d0b5e274d5fc529dcb4764d9e4e

It just need to be pushed to server. Howev er unfortunately this has to do @Jazzpirate.

**Comment by Shadow992** [comment]
Closed as it should work now (if @Jazzpirate pushed latest version).

**Comment by kohlhase** [comment]
I am sure he will, once he is back.
