### ISSUE TITLE
implement undo for the interactions

### ISSUE THREAD

**Issue by kohlhase** [UniFormal/TGView#16]
For instance when we cluster some nodes, then we would like to have an undo, because we often get the selection wrong. The granularity of undo  should be at each click. So that when I undo the clustering, the nodes should still be selected.

**Comment by Shadow992** [comment]
A tough thing to implement, but I will keep it in mind!

**Comment by Shadow992** [comment]
Finally implemented in commit a2a5dc9264b29dc231f417c497299ace289ea9df
