### ISSUE TITLE
uncluster interaction too hidden. 

### ISSUE THREAD

**Issue by kohlhase** [UniFormal/TGView#17]
we can cluster, but we cannot expand a cluster (I thought) 
but it exists, but it is quite hidden in the right-click menu. 
Can we make this more visible? 
E.G. by an "uncluster mode", where every select directly unclusters the node?

**Comment by Shadow992** [comment]
We could but sooner or later adding too many different menus (which are always visible) will totaly overwhelm possible users. :/

**Comment by kohlhase** [comment]
Yes, there is a design problem which can (and should) be solved.

**Comment by Shadow992** [comment]
Is this still relevant as we now have got the "Undo-Function"? For me it seems perfectly ok to have two possible ways to uncluster a cluster.

1. Undo
2. Right-Click --> Uncluster

**Comment by kohlhase** [comment]
I guess that this will do.
