### ISSUE TITLE
"show/hide by class" interface

### ISSUE THREAD

**Issue by kohlhase** [UniFormal/TGView#18]
#We have the show meta links UI for a whild and now also show alignments. And I find myself wanting to have their visibility toggleable as well. 
So I guess what we need instead is a drop-down menu "visibility" where I can toggle all kinds of things. 
All edges and nodes should have some kind of 'class' (probably they already do), and we should populate the "visibility" menu with toggles for all 'classes'. 
I think this will give useful (and UI-concentrated) interaction possibilities. The current "show meta edges" is just a special case.

**Comment by Shadow992** [comment]
I close this as I split the issue into several ones and partly implemented it in52022e308687942ae0d67bb8e792356bd07d44cb.
