### ISSUE TITLE
share button

### ISSUE THREAD

**Issue by kohlhase** [UniFormal/TGView#27]
Ich finde, wir brauchen einen schare button, der die Graph-URL auf allen medien schart (Mail, Skype; Facebook, ....)
Da sollte es ja schon JS zu geben.

**Comment by Shadow992** [comment]
Yep sharing on social media is a good idea, this may work:
http://js-socials.com/start-using/

I will try to implement this soon.

**Comment by Shadow992** [comment]
Implemented with 91d796b35217b7195185a8222b8fe9bb93132508
