### ISSUE TITLE
Allow loading graph from different sources

### ISSUE THREAD

**Issue by Shadow992** [UniFormal/TGView#34]
At the moment TGView is only able to load graph JSON files from a website or from local hard disk. However in some usecases integrating the JSON into HTML-Code or appending directly to the URI may come handy (e.g.):

www.kwarc.de/tgview.html?graphdata=JSON_DATA

**Comment by kohlhase** [comment]
getting this to work will also allow loading graphs from other situations, e.g. in MathHub presentations or Theresa's interview tool.

**Comment by Shadow992** [comment]
Implemented with 78f6daac35ba1f1780367c50f2a0fbbe7fff352b

Ok this took way longer than I expected it would. However now embedding in any HTML site is possible. The recommended way to embed the graph in HTML is by using an IFrame. The generated source in right menu simply has to be copied into HTML and works without any further requirements or manual steps.
