### ISSUE TITLE
Allow to choose graph type in the viewer

### ISSUE THREAD

**Issue by Jazzpirate** [UniFormal/TGView#4]
There are currently four different graph types: pgraph, docgraph, archivegraph and thgraph (models to come).
It would be nice if we were to switch between them in the graphviewer. Ideally the list of graph types would come from MMT via json. I propose the url <mmtUrl>/:jgraph/types

**Comment by kohlhase** [comment]
When you generate the JSON, then you should probably also include a one-line explanation (e.g. for a hover message) on what these graph types give you (in terms of understanting the modular structure).

**Comment by Shadow992** [comment]
@Jazzpirate Is this already implemented? If yes, what is the full URI to get graphtypes?
How to use the Graph-Types? Should the viewer only change the URL of e.g. 

https://mathhub.info/mh/mmt/graphs/tgview.html?type=**archivegraph**&graphdata=Teaching/KRMT

to

https://mathhub.info/mh/mmt/graphs/tgview.html?type=**pgraph**&graphdata=Teaching/KRMT

or is there more to do?

**Comment by Shadow992** [comment]
Implemented with Commits: f1424fee17ef6f5f4e37415c4a48c810b248b426 and 069568c6d6eece742f302c5997dee395c9147967
