### ISSUE TITLE
toggle showing the meta-theory relation 

### ISSUE THREAD

**Issue by kohlhase** [UniFormal/TGView#5]
Often we do not want to see it, most the time we do not, we should have a simple toggle somewhere. All the computation should be in the client for that (we know what the meta-links are).

**Comment by Shadow992** [comment]
So basically it is "show/hide" edges which are labeled as "meta-link"?

**Comment by kohlhase** [comment]
exactly

**Comment by Shadow992** [comment]
It took a bit, but finally this works, too.
The UI is getting a bit ugly. I am quite clueless how to make this things looking nicer... :/
For now this hopefully is ok, but next stepp will be to get these things in a nicer UI.

See e.g. http://neuralocean.de/graph/theorygraph.php?uri=http://neuralocean.de/graph/test/pvs.json

**Comment by kohlhase** [comment]
ah, this is very very nice and helpful. 
I am very happy to have this.
