### ISSUE TITLE
make a legend pane (or something)

### ISSUE THREAD

**Issue by kohlhase** [UniFormal/TGView#52]
Even I have trouble remembering what the various node and arrow styles are, ...
It would be very good to have a "legend" somewhere (maybe in its own slide-in pane or integrated into the right one). That tells us (depending on the mode (MPD or Archive Graph or ...) what it all means.

**Comment by Shadow992** [comment]
Implemented with 9667c2f1e9f164fe9c3f2d979912e8ca45fa9f65
