### ISSUE TITLE
Port TGView to React

### ISSUE THREAD

**Issue by Shadow992** [UniFormal/TGView#54]
To enable easy embedding in mathhub, we should port TGView to React.

**Comment by tkw1536** [comment]
@Shadow992 are there any updates on this?

**Comment by kohlhase** [comment]
Indeed, it would be very very good to have progress on this, since we would like to demo MathHub at the OpenDreamKit Evaluation at the end of this month and TGView would be one of the highlights.

**Comment by tkw1536** [comment]
@Shadow992 status?

**Comment by Shadow992** [comment]
Was a bit busy. However I plan to get it done until New Year. Hopefully earlier!
